import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { IAccountRepository } from '../../../domain/account/repositories/account.repository.interface';
import { OrganizationAccount } from '../../../domain/account/models/organization-account.model';
import { AccountDomainService } from '../../../domain/account/services/account-domain.service';
import { CreateOrganizationAccountDto } from '../dto/account.dto';

/**
 * Create Organization Command
 * Creates a new organization account
 */
@Injectable({
  providedIn: 'root'
})
export class CreateOrganizationCommand {
  private readonly accountDomain = inject(AccountDomainService);

  /**
   * Execute create organization command
   */
  execute(dto: CreateOrganizationAccountDto, repository: IAccountRepository): Observable<OrganizationAccount> {
    const now = new Date();
    
    const organization = new OrganizationAccount(
      '', // ID will be generated by database
      dto.username,
      dto.email || null,
      dto.displayName,
      dto.avatarUrl || null,
      dto.bio || null,
      now,
      now,
      dto.companyName,
      dto.website || null,
      dto.location || null,
      0, // memberCount starts at 0
      0, // teamCount starts at 0
      false // isVerified defaults to false
    );

    // Validate
    const validation = this.accountDomain.validateAccountCreation(organization);
    if (!validation.valid) {
      throw new Error(`Validation failed: ${validation.errors.join(', ')}`);
    }

    // Create via repository
    return repository.create(organization).pipe(
      map(account => account as OrganizationAccount)
    );
  }
}
