import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { IAccountRepository } from '../../../domain/account/repositories/account.repository.interface';
import { BotAccount } from '../../../domain/account/models/bot-account.model';
import { AccountDomainService } from '../../../domain/account/services/account-domain.service';
import { CreateBotAccountDto } from '../dto/account.dto';

/**
 * Create Bot Command
 * Creates a new bot account
 */
@Injectable({
  providedIn: 'root'
})
export class CreateBotCommand {
  private readonly accountDomain = inject(AccountDomainService);

  /**
   * Execute create bot command
   */
  execute(dto: CreateBotAccountDto, repository: IAccountRepository): Observable<BotAccount> {
    const now = new Date();
    
    const bot = new BotAccount(
      '', // ID will be generated by database
      dto.username,
      null, // Bots typically don't have email
      dto.displayName,
      dto.avatarUrl || null,
      dto.bio || null,
      now,
      now,
      dto.ownerId,
      dto.purpose || null,
      true, // isActive defaults to true
      null // lastActiveAt starts as null
    );

    // Validate
    const validation = this.accountDomain.validateAccountCreation(bot);
    if (!validation.valid) {
      throw new Error(`Validation failed: ${validation.errors.join(', ')}`);
    }

    // Create via repository
    return repository.create(bot).pipe(
      map(account => account as BotAccount)
    );
  }
}
