import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { IAccountRepository } from '../../../domain/account/repositories/account.repository.interface';
import { UserAccount } from '../../../domain/account/models/user-account.model';
import { AccountDomainService } from '../../../domain/account/services/account-domain.service';
import { AccountType } from '../../../domain/account/value-objects/account-type.vo';
import { CreateUserAccountDto } from '../dto/account.dto';

/**
 * Create User Account Command
 * Creates a new user account
 */
@Injectable({
  providedIn: 'root'
})
export class CreateUserAccountCommand {
  private readonly accountDomain = inject(AccountDomainService);

  /**
   * Execute create user account command
   * Note: Repository injection should be done via infrastructure layer
   */
  execute(dto: CreateUserAccountDto, repository: IAccountRepository): Observable<UserAccount> {
    const now = new Date();
    
    const userAccount = new UserAccount(
      '', // ID will be generated by database
      dto.username,
      dto.email || null,
      dto.displayName,
      dto.avatarUrl || null,
      dto.bio || null,
      now,
      now,
      dto.firstName || null,
      dto.lastName || null,
      dto.location || null,
      dto.website || null,
      false // isVerified defaults to false
    );

    // Validate
    const validation = this.accountDomain.validateAccountCreation(userAccount);
    if (!validation.valid) {
      throw new Error(`Validation failed: ${validation.errors.join(', ')}`);
    }

    // Create via repository
    return repository.create(userAccount).pipe(
      map(account => account as UserAccount)
    );
  }
}
