import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { UserAccount } from '../../../domain/account/models/user-account.model';
import { AccountRepository } from '../../../infrastructure/supabase/repositories/account.repository';
import { map } from 'rxjs/operators';
import { AccountDto, accountToDto } from '../dto/account.dto';

/**
 * Create User Account Command
 */
export interface CreateUserAccountCommand {
  username: string;
  displayName: string;
  email: string;
  avatarUrl?: string;
  bio?: string;
}

@Injectable({
  providedIn: 'root'
})
export class CreateUserAccountCommandHandler {
  constructor(private readonly accountRepository: AccountRepository) {}

  execute(command: CreateUserAccountCommand): Observable<AccountDto> {
    const userAccount = new UserAccount(
      '', // ID will be generated by the database
      command.username,
      command.displayName,
      command.email,
      command.avatarUrl || null,
      command.bio || null
    );

    if (!userAccount.validate()) {
      throw new Error('Invalid user account data');
    }

    return this.accountRepository.createUser(userAccount).pipe(
      map(accountToDto)
    );
  }
}
